In [1]:
import pandas as pd
import numpy as np

In [2]:
# load dataset
data = pd.read_csv("data.csv", header=None)

In [3]:
# set columns
columns = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "label"]
data.columns = columns

In [4]:
data.head()

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13  A14  A15 label
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202    0     +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43  560     +
2  a   24.5  0.500  u  g  q  h  1.50  t   f    0   f   g  280  824     +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100    3     +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120    0     +

In [5]:
# replace ? values with NaN to be handled properly
data = data.replace("?", np.nan)

In [6]:
# check missing values
data.isna().sum()

A1       12
A2       12
A3        0
A4        6
A5        6
A6        9
A7        9
A8        0
A9        0
A10       0
A11       0
A12       0
A13       0
A14      13
A15       0
label     0
dtype: int64

In [7]:
# drop missing values
data.dropna(inplace=True)
# data.fillna(method='bfill', inplace=True)
# check missing values
data.isna().sum()

A1       0
A2       0
A3       0
A4       0
A5       0
A6       0
A7       0
A8       0
A9       0
A10      0
A11      0
A12      0
A13      0
A14      0
A15      0
label    0
dtype: int64

In [8]:
# encode categorical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["A1"] = le.fit_transform(data["A1"])
data["A4"] = le.fit_transform(data["A4"])
data["A5"] = le.fit_transform(data["A5"])
data["A6"] = le.fit_transform(data["A6"])
data["A7"] = le.fit_transform(data["A7"])
data["A9"] = le.fit_transform(data["A9"])
data["A10"] = le.fit_transform(data["A10"])
data["A12"] = le.fit_transform(data["A12"])
data["A13"] = le.fit_transform(data["A13"])
data["label"] = le.fit_transform(data["label"])

In [9]:
data.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,label
0,1,30.83,0.000,1,0,12,7,1.25,1,1,1,0,0,202,0,0
1,0,58.67,4.460,1,0,10,3,3.04,1,1,6,0,0,43,560,0
2,0,24.5,0.500,1,0,10,3,1.50,1,0,0,0,0,280,824,0
3,1,27.83,1.540,1,0,12,7,3.75,1,1,5,1,0,100,3,0
4,1,20.17,5.625,1,0,12,7,1.71,1,0,0,0,2,120,0,0

In [19]:
# # heat map
# import seaborn as sns
# import matplotlib as plt
# from matplotlib import pyplot
# corr = data.corr()
# fig, ax = pyplot.subplots(figsize=(20,10)) 
# sns.heatmap(corr, 
#             annot=True,
#             xticklabels=corr.columns.values,
#             yticklabels=corr.columns.values)

In [20]:
 # create X and y sets
features = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15"]
X = data[["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15"]]
y = data["label"]
X.head()

   A1     A2     A3  A4  A5  A6  A7    A8  A9  A10  A11  A12  A13  A14  A15
0   1  30.83  0.000   1   0  12   7  1.25   1    1    1    0    0  202    0
1   0  58.67  4.460   1   0  10   3  3.04   1    1    6    0    0   43  560
2   0   24.5  0.500   1   0  10   3  1.50   1    0    0    0    0  280  824
3   1  27.83  1.540   1   0  12   7  3.75   1    1    5    1    0  100    3
4   1  20.17  5.625   1   0  12   7  1.71   1    0    0    0    2  120    0

In [21]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
# standadizing data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
scaler = StandardScaler().fit(X_test)
X_test = scaler.transform(X_test)

In [23]:
# Merge inputs and targets
inputs = np.concatenate((X_train, X_test), axis=0)
targets = np.concatenate((y_train, y_test), axis=0)

In [24]:
# model = Sequential()
# model.add(Dense(15, activation='relu', input_shape=(15,)))
# model.add(Dense(8, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

In [25]:
from sklearn.model_selection import KFold
folds = 5
f_score_per_fold = []
kfold = KFold(n_splits=folds, shuffle=True)

In [17]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import f1_score
batch_size = 50
no_epochs = 25
verbosity = 2
fold_no = 1
for train, test in kfold.split(inputs, targets):    
    # Define the model architecture
    model = Sequential()
    model.add(Dense(15, activation='relu', input_shape=(15,)))
    model.add(Dense(8, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(loss='binary_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])


    # Generate a print
    print('------------------------------------------------------------------------')
    print(f'Training for fold {fold_no} ...')

    # Fit data to model
    history = model.fit(inputs[train], targets[train],
                  batch_size=batch_size,
                  epochs=no_epochs,
                  verbose=verbosity)

    pred = model.predict(inputs[test])
    y_pred = []
    for i in pred:
        if(i[0] > 0.5):
            y_pred.append(1)
        else:
            y_pred.append(0)
    f_val = f1_score(targets[test], y_pred, average='macro')
    f_score_per_fold.append(f_val)
    print("F score for fold: "+str(fold_no)+" is: "+str(f_val))

    # Increase fold number
    fold_no = fold_no + 1

Using TensorFlow backend.
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING: Logging before flag parsing goes to stderr.
W0725 22:46:55.012428 139882462508864 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0725 22:46:55.029175 139882462508864 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0725 22:46:55.031736 139882462508864 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0725 22:46:55.079434 139882462508864 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0725 22:46:55.094634 139882462508864 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0725 22:46:55.098688 139882462508864 deprecation.py:323] From /home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0725 22:46:55.247096 139882462508864 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

------------------------------------------------------------------------
Training for fold 1 ...
Epoch 1/25
 - 0s - loss: 0.6926 - acc: 0.5594
Epoch 2/25
 - 0s - loss: 0.6692 - acc: 0.5766
Epoch 3/25
 - 0s - loss: 0.6512 - acc: 0.5881
Epoch 4/25
 - 0s - loss: 0.6367 - acc: 0.6111
Epoch 5/25
 - 0s - loss: 0.6240 - acc: 0.6322
Epoch 6/25
 - 0s - loss: 0.6131 - acc: 0.6360
Epoch 7/25
 - 0s - loss: 0.6029 - acc: 0.6686
Epoch 8/25
 - 0s - loss: 0.5937 - acc: 0.6782
Epoch 9/25
 - 0s - loss: 0.5842 - acc: 0.6897
Epoch 10/25
 - 0s - loss: 0.5753 - acc: 0.7031
Epoch 11/25
 - 0s - loss: 0.5665 - acc: 0.7203
Epoch 12/25
 - 0s - loss: 0.5581 - acc: 0.7299
Epoch 13/25
 - 0s - loss: 0.5501 - acc: 0.7414
Epoch 14/25
 - 0s - loss: 0.5422 - acc: 0.7490
Epoch 15/25
 - 0s - loss: 0.5343 - acc: 0.7529
Epoch 16/25
 - 0s - loss: 0.5265 - acc: 0.7625
Epoch 17/25
 - 0s - loss: 0.5189 - acc: 0.7682
Epoch 18/25
 - 0s - loss: 0.5114 - acc: 0.7720
Epoch 19/25
 - 0s - loss: 0.5039 - acc: 0.7778
Epoch 20/25
 - 0s - loss: 0.4968 - acc: 0.7854
Epoch 21/25
 - 0s - loss: 0.4900 - acc: 0.7931
Epoch 22/25
 - 0s - loss: 0.4831 - acc: 0.7989
Epoch 23/25
 - 0s - loss: 0.4767 - acc: 0.8008
Epoch 24/25
 - 0s - loss: 0.4700 - acc: 0.8046
Epoch 25/25
 - 0s - loss: 0.4637 - acc: 0.8084
F score for fold: 1 is: 0.7504761904761905
------------------------------------------------------------------------
Training for fold 2 ...
Epoch 1/25
 - 0s - loss: 0.8798 - acc: 0.3870
Epoch 2/25
 - 0s - loss: 0.8212 - acc: 0.4119
Epoch 3/25
 - 0s - loss: 0.7806 - acc: 0.4215
Epoch 4/25
 - 0s - loss: 0.7506 - acc: 0.4502
Epoch 5/25
 - 0s - loss: 0.7272 - acc: 0.4828
Epoch 6/25
 - 0s - loss: 0.7083 - acc: 0.5096
Epoch 7/25
 - 0s - loss: 0.6938 - acc: 0.5536
Epoch 8/25
 - 0s - loss: 0.6809 - acc: 0.5805
Epoch 9/25
 - 0s - loss: 0.6697 - acc: 0.6054
Epoch 10/25
 - 0s - loss: 0.6597 - acc: 0.6245
Epoch 11/25
 - 0s - loss: 0.6506 - acc: 0.6494
Epoch 12/25
 - 0s - loss: 0.6423 - acc: 0.6724
Epoch 13/25
 - 0s - loss: 0.6344 - acc: 0.6916
Epoch 14/25
 - 0s - loss: 0.6271 - acc: 0.6973
Epoch 15/25
 - 0s - loss: 0.6200 - acc: 0.7031
Epoch 16/25
 - 0s - loss: 0.6130 - acc: 0.7146
Epoch 17/25
 - 0s - loss: 0.6060 - acc: 0.7184
Epoch 18/25
 - 0s - loss: 0.5995 - acc: 0.7337
Epoch 19/25
 - 0s - loss: 0.5930 - acc: 0.7280
Epoch 20/25
 - 0s - loss: 0.5867 - acc: 0.7337
Epoch 21/25
 - 0s - loss: 0.5805 - acc: 0.7395
Epoch 22/25
 - 0s - loss: 0.5745 - acc: 0.7471
Epoch 23/25
 - 0s - loss: 0.5682 - acc: 0.7567
Epoch 24/25
 - 0s - loss: 0.5617 - acc: 0.7682
Epoch 25/25
 - 0s - loss: 0.5555 - acc: 0.7759
F score for fold: 2 is: 0.6237617959087978
------------------------------------------------------------------------
Training for fold 3 ...
Epoch 1/25
 - 0s - loss: 0.7380 - acc: 0.5441
Epoch 2/25
 - 0s - loss: 0.7222 - acc: 0.5460
Epoch 3/25
 - 0s - loss: 0.7089 - acc: 0.5613
Epoch 4/25
 - 0s - loss: 0.6973 - acc: 0.5824
Epoch 5/25
 - 0s - loss: 0.6872 - acc: 0.5900
Epoch 6/25
 - 0s - loss: 0.6777 - acc: 0.5843
Epoch 7/25
 - 0s - loss: 0.6685 - acc: 0.5977
Epoch 8/25
 - 0s - loss: 0.6604 - acc: 0.6130
Epoch 9/25
 - 0s - loss: 0.6525 - acc: 0.6322
Epoch 10/25
 - 0s - loss: 0.6447 - acc: 0.6667
Epoch 11/25
 - 0s - loss: 0.6373 - acc: 0.6801
Epoch 12/25
 - 0s - loss: 0.6301 - acc: 0.6935
Epoch 13/25
 - 0s - loss: 0.6228 - acc: 0.7031
Epoch 14/25
 - 0s - loss: 0.6155 - acc: 0.7203
Epoch 15/25
 - 0s - loss: 0.6086 - acc: 0.7203
Epoch 16/25
 - 0s - loss: 0.6018 - acc: 0.7356
Epoch 17/25
 - 0s - loss: 0.5949 - acc: 0.7548
Epoch 18/25
 - 0s - loss: 0.5880 - acc: 0.7644
Epoch 19/25
 - 0s - loss: 0.5811 - acc: 0.7739
Epoch 20/25
 - 0s - loss: 0.5741 - acc: 0.7816
Epoch 21/25
 - 0s - loss: 0.5671 - acc: 0.7893
Epoch 22/25
 - 0s - loss: 0.5604 - acc: 0.7874
Epoch 23/25
 - 0s - loss: 0.5536 - acc: 0.7931
Epoch 24/25
 - 0s - loss: 0.5468 - acc: 0.8008
Epoch 25/25
 - 0s - loss: 0.5400 - acc: 0.8046
F score for fold: 3 is: 0.8098693759071118
------------------------------------------------------------------------
Training for fold 4 ...
Epoch 1/25
 - 0s - loss: 0.6779 - acc: 0.5660
Epoch 2/25
 - 0s - loss: 0.6733 - acc: 0.5717
Epoch 3/25
 - 0s - loss: 0.6686 - acc: 0.5813
Epoch 4/25
 - 0s - loss: 0.6646 - acc: 0.5870
Epoch 5/25
 - 0s - loss: 0.6605 - acc: 0.6004
Epoch 6/25
 - 0s - loss: 0.6564 - acc: 0.6080
Epoch 7/25
 - 0s - loss: 0.6527 - acc: 0.6157
Epoch 8/25
 - 0s - loss: 0.6488 - acc: 0.6348
Epoch 9/25
 - 0s - loss: 0.6449 - acc: 0.6405
Epoch 10/25
 - 0s - loss: 0.6412 - acc: 0.6520
Epoch 11/25
 - 0s - loss: 0.6374 - acc: 0.6520
Epoch 12/25
 - 0s - loss: 0.6335 - acc: 0.6654
Epoch 13/25
 - 0s - loss: 0.6296 - acc: 0.6692
Epoch 14/25
 - 0s - loss: 0.6255 - acc: 0.6750
Epoch 15/25
 - 0s - loss: 0.6215 - acc: 0.6750
Epoch 16/25
 - 0s - loss: 0.6175 - acc: 0.6826
Epoch 17/25
 - 0s - loss: 0.6133 - acc: 0.6826
Epoch 18/25
 - 0s - loss: 0.6089 - acc: 0.6902
Epoch 19/25
 - 0s - loss: 0.6046 - acc: 0.6960
Epoch 20/25
 - 0s - loss: 0.6000 - acc: 0.7055
Epoch 21/25
 - 0s - loss: 0.5954 - acc: 0.7094
Epoch 22/25
 - 0s - loss: 0.5907 - acc: 0.7208
Epoch 23/25
 - 0s - loss: 0.5860 - acc: 0.7228
Epoch 24/25
 - 0s - loss: 0.5812 - acc: 0.7208
Epoch 25/25
 - 0s - loss: 0.5762 - acc: 0.7304
F score for fold: 4 is: 0.7281045751633987
------------------------------------------------------------------------
Training for fold 5 ...
Epoch 1/25
 - 0s - loss: 0.7380 - acc: 0.4264
Epoch 2/25
 - 0s - loss: 0.7138 - acc: 0.4608
Epoch 3/25
 - 0s - loss: 0.6934 - acc: 0.5220
Epoch 4/25
 - 0s - loss: 0.6753 - acc: 0.5602
Epoch 5/25
 - 0s - loss: 0.6597 - acc: 0.6042
Epoch 6/25
 - 0s - loss: 0.6453 - acc: 0.6291
Epoch 7/25
 - 0s - loss: 0.6326 - acc: 0.6424
Epoch 8/25
 - 0s - loss: 0.6204 - acc: 0.6711
Epoch 9/25
 - 0s - loss: 0.6091 - acc: 0.6807
Epoch 10/25
 - 0s - loss: 0.5985 - acc: 0.6864
Epoch 11/25
 - 0s - loss: 0.5886 - acc: 0.7055
Epoch 12/25
 - 0s - loss: 0.5789 - acc: 0.7170
Epoch 13/25
 - 0s - loss: 0.5698 - acc: 0.7247
Epoch 14/25
 - 0s - loss: 0.5608 - acc: 0.7400
Epoch 15/25
 - 0s - loss: 0.5519 - acc: 0.7533
Epoch 16/25
 - 0s - loss: 0.5432 - acc: 0.7629
Epoch 17/25
 - 0s - loss: 0.5346 - acc: 0.7706
Epoch 18/25
 - 0s - loss: 0.5265 - acc: 0.7859
Epoch 19/25
 - 0s - loss: 0.5184 - acc: 0.7897
Epoch 20/25
 - 0s - loss: 0.5106 - acc: 0.8069
Epoch 21/25
 - 0s - loss: 0.5029 - acc: 0.8088
Epoch 22/25
 - 0s - loss: 0.4954 - acc: 0.8145
Epoch 23/25
 - 0s - loss: 0.4881 - acc: 0.8203
Epoch 24/25
 - 0s - loss: 0.4809 - acc: 0.8184
Epoch 25/25
 - 0s - loss: 0.4737 - acc: 0.8279
F score for fold: 5 is: 0.803494769937723

In [18]:
# == Provide average scores ==
print('------------------------------------------------------------------------')
print('F Score per fold')
for i in range(0, len(f_score_per_fold)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - F Score: {f_score_per_fold[i]}')
print('------------------------------------------------------------------------')
print(f'> Avg F score: {np.mean(f_score_per_fold)}')
print('------------------------------------------------------------------------')

------------------------------------------------------------------------
F Score per fold
------------------------------------------------------------------------
> Fold 1 - F Score: 0.7504761904761905
------------------------------------------------------------------------
> Fold 2 - F Score: 0.6237617959087978
------------------------------------------------------------------------
> Fold 3 - F Score: 0.8098693759071118
------------------------------------------------------------------------
> Fold 4 - F Score: 0.7281045751633987
------------------------------------------------------------------------
> Fold 5 - F Score: 0.803494769937723
------------------------------------------------------------------------
> Avg F score: 0.7431413414786444
------------------------------------------------------------------------