In [1]:
import pandas as pd
import numpy as np

In [2]:
# load dataset
data = pd.read_csv("data.csv", header=None)

In [3]:
# set columns
columns = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "label"]
data.columns = columns

In [4]:
data.head()

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13  A14  A15 label
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202    0     +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43  560     +
2  a   24.5  0.500  u  g  q  h  1.50  t   f    0   f   g  280  824     +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100    3     +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120    0     +

In [5]:
# replace ? values with NaN to be handled properly
data = data.replace("?", np.nan)

In [6]:
# check missing values
data.isna().sum()

A1       12
A2       12
A3        0
A4        6
A5        6
A6        9
A7        9
A8        0
A9        0
A10       0
A11       0
A12       0
A13       0
A14      13
A15       0
label     0
dtype: int64

In [7]:
# drop missing values
data.dropna(inplace=True)
# data.fillna(method='bfill', inplace=True)
# check missing values
data.isna().sum()

A1       0
A2       0
A3       0
A4       0
A5       0
A6       0
A7       0
A8       0
A9       0
A10      0
A11      0
A12      0
A13      0
A14      0
A15      0
label    0
dtype: int64

In [8]:
# encode categorical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["A1"] = le.fit_transform(data["A1"])
data["A4"] = le.fit_transform(data["A4"])
data["A5"] = le.fit_transform(data["A5"])
data["A6"] = le.fit_transform(data["A6"])
data["A7"] = le.fit_transform(data["A7"])
data["A9"] = le.fit_transform(data["A9"])
data["A10"] = le.fit_transform(data["A10"])
data["A12"] = le.fit_transform(data["A12"])
data["A13"] = le.fit_transform(data["A13"])
data["label"] = le.fit_transform(data["label"])

In [9]:
data.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,label
0,1,30.83,0.000,1,0,12,7,1.25,1,1,1,0,0,202,0,0
1,0,58.67,4.460,1,0,10,3,3.04,1,1,6,0,0,43,560,0
2,0,24.5,0.500,1,0,10,3,1.50,1,0,0,0,0,280,824,0
3,1,27.83,1.540,1,0,12,7,3.75,1,1,5,1,0,100,3,0
4,1,20.17,5.625,1,0,12,7,1.71,1,0,0,0,2,120,0,0

In [10]:
# # heat map
# import seaborn as sns
# import matplotlib as plt
# from matplotlib import pyplot
# corr = data.corr()
# fig, ax = pyplot.subplots(figsize=(20,10)) 
# sns.heatmap(corr, 
#             annot=True,
#             xticklabels=corr.columns.values,
#             yticklabels=corr.columns.values)

In [11]:
 # create X and y sets
features = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15"]
X = data[["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15"]]
y = data["label"]
X.head()

   A1     A2     A3  A4  A5  A6  A7    A8  A9  A10  A11  A12  A13  A14  A15
0   1  30.83  0.000   1   0  12   7  1.25   1    1    1    0    0  202    0
1   0  58.67  4.460   1   0  10   3  3.04   1    1    6    0    0   43  560
2   0   24.5  0.500   1   0  10   3  1.50   1    0    0    0    0  280  824
3   1  27.83  1.540   1   0  12   7  3.75   1    1    5    1    0  100    3
4   1  20.17  5.625   1   0  12   7  1.71   1    0    0    0    2  120    0

In [12]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# standadizing data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
scaler = StandardScaler().fit(X_test)
X_test = scaler.transform(X_test)

In [14]:
# Merge inputs and targets
inputs = np.concatenate((X_train, X_test), axis=0)
targets = np.concatenate((y_train, y_test), axis=0)

In [15]:
# model = Sequential()
# model.add(Dense(15, activation='relu', input_shape=(15,)))
# model.add(Dense(8, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

In [16]:
from sklearn.model_selection import KFold
folds = 5
f_score_per_fold = []
kfold = KFold(n_splits=folds, shuffle=True)

In [17]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import f1_score
batch_size = 50
no_epochs = 25
verbosity = 2
fold_no = 1
loss_function = "binary_crossentropy" 
for train, test in kfold.split(inputs, targets):    
    # Define the model architecture
    model = Sequential()
    model.add(Dense(15, activation='relu', input_shape=(15,)))
    model.add(Dense(30, activation='relu'))
    model.add(Dense(45, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(loss=loss_function,
              optimizer='sgd',
              metrics=['accuracy'])


    # Generate a print
    print('------------------------------------------------------------------------')
    print(f'Training for fold {fold_no} ...')

    # Fit data to model
    history = model.fit(inputs[train], targets[train],
                  batch_size=batch_size,
                  epochs=no_epochs,
                  verbose=verbosity)

    pred = model.predict(inputs[test])
    y_pred = []
    for i in pred:
        if(i[0] > 0.5):
            y_pred.append(1)
        else:
            y_pred.append(0)
    f_val = f1_score(targets[test], y_pred, average='macro')
    f_score_per_fold.append(f_val)
    print("F score for fold: "+str(fold_no)+" is: "+str(f_val))

    # Increase fold number
    fold_no = fold_no + 1

Using TensorFlow backend.
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/sidathm/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING: Logging before flag parsing goes to stderr.
W0725 23:08:35.929216 139873853687616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0725 23:08:35.943782 139873853687616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0725 23:08:35.945856 139873853687616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0725 23:08:35.999954 139873853687616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0725 23:08:36.024120 139873853687616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0725 23:08:36.029515 139873853687616 deprecation.py:323] From /home/sidathm/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0725 23:08:36.239920 139873853687616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

------------------------------------------------------------------------
Training for fold 1 ...
Epoch 1/25
 - 0s - loss: 0.6847 - acc: 0.5843
Epoch 2/25
 - 0s - loss: 0.6775 - acc: 0.6073
Epoch 3/25
 - 0s - loss: 0.6703 - acc: 0.6245
Epoch 4/25
 - 0s - loss: 0.6634 - acc: 0.6437
Epoch 5/25
 - 0s - loss: 0.6569 - acc: 0.6762
Epoch 6/25
 - 0s - loss: 0.6504 - acc: 0.6935
Epoch 7/25
 - 0s - loss: 0.6437 - acc: 0.7107
Epoch 8/25
 - 0s - loss: 0.6373 - acc: 0.7280
Epoch 9/25
 - 0s - loss: 0.6308 - acc: 0.7356
Epoch 10/25
 - 0s - loss: 0.6242 - acc: 0.7395
Epoch 11/25
 - 0s - loss: 0.6175 - acc: 0.7471
Epoch 12/25
 - 0s - loss: 0.6105 - acc: 0.7529
Epoch 13/25
 - 0s - loss: 0.6033 - acc: 0.7529
Epoch 14/25
 - 0s - loss: 0.5959 - acc: 0.7605
Epoch 15/25
 - 0s - loss: 0.5885 - acc: 0.7625
Epoch 16/25
 - 0s - loss: 0.5808 - acc: 0.7682
Epoch 17/25
 - 0s - loss: 0.5727 - acc: 0.7701
Epoch 18/25
 - 0s - loss: 0.5645 - acc: 0.7778
Epoch 19/25
 - 0s - loss: 0.5564 - acc: 0.7816
Epoch 20/25
 - 0s - loss: 0.5481 - acc: 0.7854
Epoch 21/25
 - 0s - loss: 0.5394 - acc: 0.7893
Epoch 22/25
 - 0s - loss: 0.5307 - acc: 0.7950
Epoch 23/25
 - 0s - loss: 0.5219 - acc: 0.7969
Epoch 24/25
 - 0s - loss: 0.5131 - acc: 0.8027
Epoch 25/25
 - 0s - loss: 0.5047 - acc: 0.8103
F score for fold: 1 is: 0.7297376952549367
------------------------------------------------------------------------
Training for fold 2 ...
Epoch 1/25
 - 0s - loss: 0.6749 - acc: 0.5958
Epoch 2/25
 - 0s - loss: 0.6683 - acc: 0.6226
Epoch 3/25
 - 0s - loss: 0.6620 - acc: 0.6456
Epoch 4/25
 - 0s - loss: 0.6552 - acc: 0.6590
Epoch 5/25
 - 0s - loss: 0.6487 - acc: 0.6839
Epoch 6/25
 - 0s - loss: 0.6422 - acc: 0.7011
Epoch 7/25
 - 0s - loss: 0.6359 - acc: 0.7184
Epoch 8/25
 - 0s - loss: 0.6293 - acc: 0.7299
Epoch 9/25
 - 0s - loss: 0.6226 - acc: 0.7414
Epoch 10/25
 - 0s - loss: 0.6158 - acc: 0.7529
Epoch 11/25
 - 0s - loss: 0.6089 - acc: 0.7625
Epoch 12/25
 - 0s - loss: 0.6017 - acc: 0.7605
Epoch 13/25
 - 0s - loss: 0.5945 - acc: 0.7701
Epoch 14/25
 - 0s - loss: 0.5874 - acc: 0.7778
Epoch 15/25
 - 0s - loss: 0.5799 - acc: 0.7816
Epoch 16/25
 - 0s - loss: 0.5722 - acc: 0.7874
Epoch 17/25
 - 0s - loss: 0.5646 - acc: 0.7931
Epoch 18/25
 - 0s - loss: 0.5566 - acc: 0.7969
Epoch 19/25
 - 0s - loss: 0.5487 - acc: 0.8008
Epoch 20/25
 - 0s - loss: 0.5405 - acc: 0.8008
Epoch 21/25
 - 0s - loss: 0.5324 - acc: 0.8008
Epoch 22/25
 - 0s - loss: 0.5245 - acc: 0.8008
Epoch 23/25
 - 0s - loss: 0.5165 - acc: 0.8027
Epoch 24/25
 - 0s - loss: 0.5084 - acc: 0.8046
Epoch 25/25
 - 0s - loss: 0.5003 - acc: 0.8027
F score for fold: 2 is: 0.8664627930682977
------------------------------------------------------------------------
Training for fold 3 ...
Epoch 1/25
 - 0s - loss: 0.6883 - acc: 0.5268
Epoch 2/25
 - 0s - loss: 0.6768 - acc: 0.5805
Epoch 3/25
 - 0s - loss: 0.6659 - acc: 0.6226
Epoch 4/25
 - 0s - loss: 0.6557 - acc: 0.6533
Epoch 5/25
 - 0s - loss: 0.6458 - acc: 0.6916
Epoch 6/25
 - 0s - loss: 0.6360 - acc: 0.7280
Epoch 7/25
 - 0s - loss: 0.6269 - acc: 0.7395
Epoch 8/25
 - 0s - loss: 0.6177 - acc: 0.7548
Epoch 9/25
 - 0s - loss: 0.6089 - acc: 0.7605
Epoch 10/25
 - 0s - loss: 0.6003 - acc: 0.7701
Epoch 11/25
 - 0s - loss: 0.5916 - acc: 0.7797
Epoch 12/25
 - 0s - loss: 0.5833 - acc: 0.7874
Epoch 13/25
 - 0s - loss: 0.5754 - acc: 0.7912
Epoch 14/25
 - 0s - loss: 0.5673 - acc: 0.7969
Epoch 15/25
 - 0s - loss: 0.5595 - acc: 0.7989
Epoch 16/25
 - 0s - loss: 0.5518 - acc: 0.8084
Epoch 17/25
 - 0s - loss: 0.5443 - acc: 0.8103
Epoch 18/25
 - 0s - loss: 0.5371 - acc: 0.8161
Epoch 19/25
 - 0s - loss: 0.5298 - acc: 0.8199
Epoch 20/25
 - 0s - loss: 0.5225 - acc: 0.8218
Epoch 21/25
 - 0s - loss: 0.5154 - acc: 0.8257
Epoch 22/25
 - 0s - loss: 0.5085 - acc: 0.8257
Epoch 23/25
 - 0s - loss: 0.5018 - acc: 0.8276
Epoch 24/25
 - 0s - loss: 0.4953 - acc: 0.8314
Epoch 25/25
 - 0s - loss: 0.4889 - acc: 0.8314
F score for fold: 3 is: 0.7921490274431451
------------------------------------------------------------------------
Training for fold 4 ...
Epoch 1/25
 - 0s - loss: 0.6872 - acc: 0.5660
Epoch 2/25
 - 0s - loss: 0.6798 - acc: 0.6023
Epoch 3/25
 - 0s - loss: 0.6729 - acc: 0.6157
Epoch 4/25
 - 0s - loss: 0.6661 - acc: 0.6482
Epoch 5/25
 - 0s - loss: 0.6595 - acc: 0.6597
Epoch 6/25
 - 0s - loss: 0.6527 - acc: 0.6730
Epoch 7/25
 - 0s - loss: 0.6461 - acc: 0.6883
Epoch 8/25
 - 0s - loss: 0.6390 - acc: 0.7094
Epoch 9/25
 - 0s - loss: 0.6321 - acc: 0.7189
Epoch 10/25
 - 0s - loss: 0.6249 - acc: 0.7323
Epoch 11/25
 - 0s - loss: 0.6178 - acc: 0.7495
Epoch 12/25
 - 0s - loss: 0.6106 - acc: 0.7495
Epoch 13/25
 - 0s - loss: 0.6032 - acc: 0.7572
Epoch 14/25
 - 0s - loss: 0.5955 - acc: 0.7591
Epoch 15/25
 - 0s - loss: 0.5883 - acc: 0.7629
Epoch 16/25
 - 0s - loss: 0.5805 - acc: 0.7744
Epoch 17/25
 - 0s - loss: 0.5728 - acc: 0.7897
Epoch 18/25
 - 0s - loss: 0.5650 - acc: 0.7897
Epoch 19/25
 - 0s - loss: 0.5572 - acc: 0.8031
Epoch 20/25
 - 0s - loss: 0.5494 - acc: 0.8031
Epoch 21/25
 - 0s - loss: 0.5415 - acc: 0.8069
Epoch 22/25
 - 0s - loss: 0.5334 - acc: 0.8126
Epoch 23/25
 - 0s - loss: 0.5259 - acc: 0.8107
Epoch 24/25
 - 0s - loss: 0.5179 - acc: 0.8107
Epoch 25/25
 - 0s - loss: 0.5103 - acc: 0.8145
F score for fold: 4 is: 0.8151011069197946
------------------------------------------------------------------------
Training for fold 5 ...
Epoch 1/25
 - 0s - loss: 0.7188 - acc: 0.4570
Epoch 2/25
 - 0s - loss: 0.6927 - acc: 0.4608
Epoch 3/25
 - 0s - loss: 0.6728 - acc: 0.4761
Epoch 4/25
 - 0s - loss: 0.6562 - acc: 0.5182
Epoch 5/25
 - 0s - loss: 0.6428 - acc: 0.5927
Epoch 6/25
 - 0s - loss: 0.6308 - acc: 0.6979
Epoch 7/25
 - 0s - loss: 0.6197 - acc: 0.7572
Epoch 8/25
 - 0s - loss: 0.6097 - acc: 0.7763
Epoch 9/25
 - 0s - loss: 0.6004 - acc: 0.7897
Epoch 10/25
 - 0s - loss: 0.5915 - acc: 0.8069
Epoch 11/25
 - 0s - loss: 0.5829 - acc: 0.8069
Epoch 12/25
 - 0s - loss: 0.5743 - acc: 0.8107
Epoch 13/25
 - 0s - loss: 0.5661 - acc: 0.8126
Epoch 14/25
 - 0s - loss: 0.5580 - acc: 0.8164
Epoch 15/25
 - 0s - loss: 0.5496 - acc: 0.8241
Epoch 16/25
 - 0s - loss: 0.5412 - acc: 0.8241
Epoch 17/25
 - 0s - loss: 0.5329 - acc: 0.8241
Epoch 18/25
 - 0s - loss: 0.5248 - acc: 0.8241
Epoch 19/25
 - 0s - loss: 0.5168 - acc: 0.8298
Epoch 20/25
 - 0s - loss: 0.5088 - acc: 0.8279
Epoch 21/25
 - 0s - loss: 0.5010 - acc: 0.8298
Epoch 22/25
 - 0s - loss: 0.4936 - acc: 0.8375
Epoch 23/25
 - 0s - loss: 0.4864 - acc: 0.8432
Epoch 24/25
 - 0s - loss: 0.4793 - acc: 0.8394
Epoch 25/25
 - 0s - loss: 0.4722 - acc: 0.8432
F score for fold: 5 is: 0.8452380952380952

In [18]:
# == Provide average scores ==
print('------------------------------------------------------------------------')
print('F Score per fold')
for i in range(0, len(f_score_per_fold)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - F Score: {f_score_per_fold[i]}')
print('------------------------------------------------------------------------')
print(f'> Avg F score: {np.mean(f_score_per_fold)}')
print('------------------------------------------------------------------------')

------------------------------------------------------------------------
F Score per fold
------------------------------------------------------------------------
> Fold 1 - F Score: 0.7297376952549367
------------------------------------------------------------------------
> Fold 2 - F Score: 0.8664627930682977
------------------------------------------------------------------------
> Fold 3 - F Score: 0.7921490274431451
------------------------------------------------------------------------
> Fold 4 - F Score: 0.8151011069197946
------------------------------------------------------------------------
> Fold 5 - F Score: 0.8452380952380952
------------------------------------------------------------------------
> Avg F score: 0.809737743584854
------------------------------------------------------------------------